### PR TITLE
Setting up status checks files

### PR DESCRIPTION
**Pull request by averywpx**
Setting up status checks files

### CODE REVIEW

**Comment by klaricch** [comment]
other than that one change looks good to me, although curious if @phildarnowsky-broad has any other suggestions for status checks/basic repo setup

**Review by klaricch — CHANGES_REQUESTED** [review]

**Comment by phildarnowsky-broad** [comment]
> other than that one change looks good to me, although curious if @phildarnowsky-broad has any other suggestions for status checks/basic repo setup

I can get by in Python but my knowledge of it is still fairly basic, so I'm not clear on what the established best practices are for setting up a new project. One suggestion I would make in general, though, which (I may have missed it) it looks like you haven't yet done here, would be to add support for automated tests, and to get in the habit of writing them as you go. Writing tests takes practice, and it will slow your coding down at first, but it turns out that the ROI on time spent writing them is very high, because you spend so much less of your time fixing bugs that got through to production.

**Comment by averywpx** [comment]
We decide not to set up the automated tests as for now, since the code in this repo won't be reused as much as gnomad_method.

**Comment by klaricch** [comment]
> @averywpx @klaricch I had a look around, and this looks like a very good introduction to testing in Python, if you might find such a thing useful: https://realpython.com/python-testing/

This looks like a great resource. I've been meaning to look into automated tests and think it would be good for the team to incorporate in the future - thanks @phildarnowsky-broad !

**Review by klaricch — APPROVED** [review]

**Comment by phildarnowsky-broad** [comment]
Glad to help! Hope you find that useful. And I really can't overstate how
strongly I recommend automated tests; for certain reasons, they're
especially important if you're working in Python or a similar language.

**Pull request merged**
